(function () {
  var price = "Kurbada does not sell this motorcycle and does not publish a price for it. A dealer quote changes with the year, the variant, and any promo. Match parts to the model on your OR/CR.";
  var tire = " If you replace a tire, read the full size on the sidewall. The Beast listing is a tubeless tire in 13, 14, and 17 inch, and only for a tubeless rim.";
  var rider = " Helmets, gloves, a balaclava, and pants are on the accessories page. They fit the rider.";
  var brush = " The wheel brush is a cleaning kit for every motorcycle. It is not for brake discs.";

  function bike(about, cls, drive, engine, more) {
    return {
      about: about,
      specs: [["Class", cls], ["Drive", drive], ["Engine", engine]],
      price: price,
      more: more + rider + brush
    };
  }

  window.KURBADA_BIKES = {
    "honda-wave": bike("A Honda Wave is a daily underbone for work and short trips. Philippine units are sold in more than one displacement, so the engine stamp matters more than the Wave badge.", "Underbone", "Manual", "110 and 125 classes are both sold under the Wave name. Read the number on the engine.", "No Wave-only part is in the catalog yet." + tire),
    "honda-xrm": bike("The Honda XRM is a step-through underbone used as a daily bike. The familiar Philippine model is the XRM 125, including the DS variants.", "Underbone", "Manual", "The common class is 125. Confirm the letters on the engine before you order a panel or a sprocket.", "No XRM-only part is in the catalog yet." + tire),
    "honda-tmx": bike("The Honda TMX is a business underbone. The line includes the TMX 125 and the larger TMX Supremo, so one TMX part does not fit every TMX.", "Underbone", "Manual", "125 on the standard TMX. The Supremo is a larger engine. Read the case.", "No TMX-only part is in the catalog yet." + tire),
    "yamaha-sniper": bike("The Yamaha Sniper 155 is a liquid-cooled underbone built for riders who want a manual gearbox and a 155 class engine.", "Underbone", "Manual", "155 class, liquid-cooled. Body generations still differ, so match the year on the OR/CR for any cover or fairing.", "No Sniper-only part is in the catalog yet." + tire),
    "suzuki-raider": bike("The Suzuki Raider in this list is the R150 family, a manual underbone. Carburetor and FI years do not share every part.", "Underbone", "Manual", "150 class. Confirm R150 or R150 FI on the papers before you order.", "No Raider-only part is in the catalog yet." + tire),
    "suzuki-smash-110": bike("The Suzuki Smash 110 is a small work underbone. The catalog handle-bolt set is listed for this model and the Smash 115 only.", "Underbone", "Manual", "110 class, four-stroke. Do not use the bolt set on a Click, a Wave, or another Suzuki.", "The six-piece HENG / SC CNC Siam handle bolt set is listed for Smash 110 and Smash 115." + tire),
    "suzuki-smash-115": bike("The Suzuki Smash 115 is the next small Smash underbone. The same handle-bolt set is listed for the 110 and the 115, and for no other bike.", "Underbone", "Manual", "Sold as Smash 115. Read the engine number anyway, because a nearby Smash year can use a different cover.", "The six-piece handle bolt set is listed for Smash 110 and Smash 115." + tire),
    "kawasaki-barako": bike("The Kawasaki Barako is a larger underbone, the one riders mean when they say Barako II.", "Underbone", "Manual", "175 class on the Barako II. Confirm the model if the bike is an older Barako.", "No Barako-only part is in the catalog yet." + tire),
    "kawasaki-ct": bike("The Kawasaki CT is a small utility bike. In the Philippines that name usually means the CT100, and a later CT can differ.", "Utility underbone", "Manual", "Often the CT100. Read the model stamp before you order a sprocket, a tire, or a panel.", "No CT-only part is in the catalog yet." + tire),
    "motorstar": bike("MotorStar is a local brand with several underbones and small bikes. The brand name is not one model.", "Local market", "Depends on the model", "Read the engine case. A MotorStar 110 and a MotorStar 150 do not share parts.", "No MotorStar-only part is in the catalog yet." + tire),
    "rusi": bike("Rusi is a local brand with many models. This button is the brand, not the Macho TC150. A TC150 cover is not a cover for every Rusi.", "Local market", "Depends on the model", "Read the model on the side panel and the engine number.", "The Macho TC150 has its own button. The battery side cover is listed only for that model." + tire),
    "rusi-macho-tc150": bike("The Rusi Macho TC150 is one model. The catalog side cover is a left-and-right battery pair with the Macho TC150 sticker, shown in blue, black, and red.", "Underbone", "Manual", "The model name is Macho TC150. Confirm that name on the bike before you order the cover.", "Order the cover only for a Macho TC150. Pick the color that matches the bodywork you already have." + tire),
    "skygo": bike("Skygo is a local brand with more than one small motorcycle. The badge is not a single spec sheet.", "Local market", "Depends on the model", "Read the displacement on the engine. Do not assume a Skygo part fits every Skygo.", "No Skygo-only part is in the catalog yet." + tire),

    "honda-beat": bike("The Honda BeAT is a small step-through scooter for city riding. ESP and standard versions exist, and they do not share every panel.", "Scooter", "Automatic CVT", "110 class. Match the year if you are buying bodywork.", "No BeAT-only part is in the catalog yet." + tire),
    "honda-click": bike("The Honda Click is a step-through scooter. Click 125 and Click 160 are different bikes.", "Scooter", "Automatic CVT", "125 or 160, depending on the year. Read the side cover before you order a tire or a panel.", "No Click-only part is in the catalog yet." + tire),
    "honda-airblade": bike("The Honda Airblade is a step-through scooter sold in more than one displacement.", "Scooter", "Automatic CVT", "125 and 160 classes have both used the Airblade name. Read the model year.", "No Airblade-only part is in the catalog yet." + tire),
    "honda-pcx": bike("The Honda PCX is a larger step-through scooter. The recent Philippine PCX is the 160. Older units can be a 150.", "Scooter", "Automatic CVT", "160 on current units. A 150 on older units. The number is on the body.", "No PCX-only part is in the catalog yet." + tire),
    "honda-adv": bike("The Honda ADV is the adventure-styled scooter in the Click family. ADV150 and ADV160 are not the same bike.", "Adventure scooter", "Automatic CVT", "150 on the first ADV, 160 on the later ADV. Match the badge on the side.", "No ADV-only part is in the catalog yet." + tire),
    "yamaha-mio": bike("Yamaha Mio is a family, not one scooter. Mio i 125, Mio Gear, Mio Soul, and Mio Gravis each have their own body.", "Scooter", "Automatic CVT", "Most current Mios are 125 class. Confirm the model name on the panel.", "No Mio-only part is in the catalog yet." + tire),
    "yamaha-aerox": bike("The Yamaha Aerox is a 155 scooter with a sport body. V1 and V2 do not share every panel or every exhaust fitment.", "Scooter", "Automatic CVT", "155 class. Name the version, V1 or V2, before you order bodywork or a pipe.", "No Aerox-only part is in the catalog yet. An aftermarket pipe still has to name this version on the listing." + tire),
    "yamaha-nmax": bike("The Yamaha NMAX is a 155 maxi-style scooter. Connected and standard trims, and the later body, do not share every part.", "Scooter", "Automatic CVT", "155 class. Match V1, V2, or the later body before you order a panel or a pipe.", "No NMAX-only part is in the catalog yet." + tire),
    "yamaha-xmax": bike("The Yamaha XMAX is a larger scooter than the NMAX. It is the 300 class bike in the Yamaha scooter line sold here.", "Maxi scooter", "Automatic CVT", "300 class. Do not order an NMAX tire or panel for an XMAX.", "No XMAX-only part is in the catalog yet. Check the sidewall before any tire. A 13 inch commuter tire is the wrong assumption."),
    "suzuki-burgman": bike("Suzuki Burgman in daily Philippine use is usually the Burgman Street. Larger Burgman touring scooters also exist and do not share parts.", "Scooter", "Automatic CVT", "Street models are in the 125 class. A full-size Burgman is a different motorcycle.", "No Burgman-only part is in the catalog yet." + tire),
    "suzuki-address": bike("The Suzuki Address is a small step-through scooter. Address years differ in displacement and in bodywork.", "Scooter", "Automatic CVT", "Often a 110 or 115 class scooter. Read the model on the papers.", "No Address-only part is in the catalog yet." + tire),
    "vespa": bike("Vespa is a range: Primavera, Sprint, GTS, and older LX and S bodies. A part for one Vespa is not a part for every Vespa.", "Scooter", "Automatic CVT", "50, 150, and 300 classes all wear the Vespa badge. Read the model and the engine.", "No Vespa-only part is in the catalog yet." + tire),
    "piaggio": bike("Piaggio scooters in this market include Liberty, Medley, and Beverly. Each is its own fitment.", "Scooter", "Automatic CVT", "Read the model. A Liberty 150 and a Beverly are not the same chassis.", "No Piaggio-only part is in the catalog yet." + tire),
    "sym": bike("SYM sells several scooters here. The brand is not one engine or one body.", "Scooter", "Automatic CVT", "Read the model name and the displacement. Do not order from the SYM badge alone.", "No SYM-only part is in the catalog yet." + tire),
    "kymco": bike("Kymco sells several scooters here, from small step-throughs to larger touring scooters.", "Scooter", "Automatic CVT", "Read the model. Like and X-Town, for example, do not share panels.", "No Kymco-only part is in the catalog yet." + tire),
    "fkm-venture": bike("The FKM Venture is an automatic scooter sold in the Philippine market. FKM is a local-market line, not a claim that Kurbada is a dealer.", "Scooter", "Automatic CVT", "Read the displacement on the engine. Do not copy a spec from a different FKM model.", "No Venture-only part is in the catalog yet." + tire),
    "fkm-hunter": bike("The FKM Hunter is an automatic scooter in the same local-market family as the Venture. It is its own model.", "Scooter", "Automatic CVT", "Read the engine stamp. A Hunter panel is not a Venture panel.", "No Hunter-only part is in the catalog yet." + tire),
    "fkm-ranger": bike("The FKM Ranger is an automatic scooter in the FKM line. Treat the model name on the body as the fitment.", "Scooter", "Automatic CVT", "Read the displacement on the case before a tire or a cover.", "No Ranger-only part is in the catalog yet." + tire),
    "fkm-mtx": bike("The FKM MTX is an automatic scooter in the FKM line. It is listed here as its own model, separate from Venture and Hunter.", "Scooter", "Automatic CVT", "Read the engine number. The MTX name is the one that has to match the part.", "No MTX-only part is in the catalog yet." + tire),
    "fkm-slick": bike("The FKM Slick is an automatic scooter in the FKM line.", "Scooter", "Automatic CVT", "Read the displacement on the engine before you order a tire or a panel.", "No Slick-only part is in the catalog yet." + tire),
    "fkm-fyro": bike("The FKM Fyro is an automatic scooter in the FKM line.", "Scooter", "Automatic CVT", "Read the model on the body and the engine number together.", "No Fyro-only part is in the catalog yet." + tire),

    "honda-cb": bike("Honda CB is a naked-bike family: CB150R, CB500, and larger CBs. The letters CB are not a size.", "Naked", "Manual", "From 150 class street bikes up through middleweight CBs. Read the full model.", "No CB-only part is in the catalog yet. Check the sidewall. A commuter 13 inch tire is the wrong assumption for these bikes."),
    "honda-cbr": bike("Honda CBR is the faired sport family. CBR150R, CBR500R, and CBR650R do not share bodywork.", "Sport", "Manual", "150, 500, and 650 are all common CBR names here. Use the full model code.", "No CBR-only part is in the catalog yet. Match the year for any fairing or exhaust."),
    "yamaha-mt": bike("Yamaha MT is a naked family. MT-15, MT-03, and MT-07 are different motorcycles.", "Naked", "Manual", "155 on the MT-15. Larger MTs step up from there. Read the number on the side.", "No MT-only part is in the catalog yet."),
    "yamaha-r15": bike("The Yamaha R15 is a small faired sport bike. V3 and V4 bodies differ.", "Sport", "Manual", "155 class. Name V3 or V4 before you order a fairing or a pipe.", "No R15-only part is in the catalog yet."),
    "kawasaki-ninja": bike("Kawasaki Ninja covers faired sport bikes from the small Ninja 250 and 400 up through the ZX line.", "Sport", "Manual", "Read the full name. A Ninja 400 part does not fit a Ninja 650 or a ZX-10R.", "No Ninja-only part is in the catalog yet."),
    "kawasaki-z": bike("Kawasaki Z is the naked family next to the Ninja. Z400, Z650, and Z900 are separate fitments.", "Naked", "Manual", "Read the number after the Z. Displacement is the model name.", "No Z-only part is in the catalog yet."),
    "kawasaki-rouser": bike("Kawasaki Rouser is the Philippine name on a family of small naked and sport bikes, including NS and N models.", "Naked", "Manual", "160, 200, and 250 classes have all worn the Rouser name. Read the side panel.", "No Rouser-only part is in the catalog yet."),
    "ktm-duke": bike("KTM Duke is a naked family. Duke 200, 250, and 390 are the common sizes, and a larger Duke is a different bike.", "Naked", "Manual", "The number in the name is the class. A 200 does not take a 390 panel.", "No Duke-only part is in the catalog yet."),
    "ktm-rc": bike("KTM RC is the faired companion to the Duke. RC 200 and RC 390 are the usual pair.", "Sport", "Manual", "200 or 390. Match the number on the fairing.", "No RC-only part is in the catalog yet."),
    "bajaj-pulsar": bike("Bajaj Pulsar is a family of naked and semi-faired bikes. N250, NS200, and older 180 or 220 models do not share parts.", "Naked", "Manual", "Read the full Pulsar name. The badge alone is not a size.", "No Pulsar-only part is in the catalog yet."),
    "bajaj-dominar": bike("The Bajaj Dominar is a small touring naked. Dominar 250 and Dominar 400 are different engines.", "Touring naked", "Manual", "250 or 400. Read the number on the side before you order a chain or a tire.", "No Dominar-only part is in the catalog yet."),
    "tvs-apache": bike("TVS Apache is a sport-naked family. RTR 160 and RTR 200 are the names riders usually mean.", "Sport naked", "Manual", "160 or 200 on the common RTR models. 2V and 4V years can differ. Read the decal.", "No Apache-only part is in the catalog yet."),
    "suzuki-gixxer": bike("The Suzuki Gixxer is a naked or faired 150, with a 250 also sold under the same name.", "Naked or sport", "Manual", "150 or 250. SF is the faired body. Match both the size and the body.", "No Gixxer-only part is in the catalog yet."),
    "suzuki-gsx": bike("Suzuki GSX covers GSX-R sport bikes and GSX-S nakeds, across many displacements.", "Sport or naked", "Manual", "Read the full code, such as GSX-R150 or GSX-S750. The letters GSX are not a size.", "No GSX-only part is in the catalog yet."),
    "cfmoto": bike("CFMoto sells nakeds and sport-touring bikes in several sizes. The brand is not one model.", "Naked and touring", "Manual", "250, 450, and 650 are all in the range. Read the model number.", "No CFMoto-only part is in the catalog yet."),
    "benelli": bike("Benelli here covers TNT nakeds, the 302, and the Leoncino. They do not share fitment.", "Naked and classic", "Manual", "Read the model. A TNT 135 and a Leoncino 500 are different motorcycles.", "No Benelli-only part is in the catalog yet."),
    "qj-motor": bike("QJ Motor is a brand with several nakeds and sport bikes. The badge is not one spec sheet.", "Naked and sport", "Manual", "Read the model number and the displacement on the papers.", "No QJ-only part is in the catalog yet."),

    "honda-crf": bike("Honda CRF covers off-road and adventure bikes from the small CRF150L up through the larger CRF rally bikes.", "Trail and adventure", "Manual", "150, 300, and larger rally models all use CRF. Read the full code.", "No CRF-only part is in the catalog yet. A commuter scooter tire is the wrong size to assume."),
    "honda-africa-twin": bike("The Honda Africa Twin is the large CRF adventure bike, the CRF1100.", "Adventure", "Manual", "1100 class on the current Africa Twin. Older Africa Twins are a different generation.", "No Africa Twin-only part is in the catalog yet."),
    "kawasaki-klx": bike("Kawasaki KLX is a trail family. KLX150, KLX230, and KLX250 do not share wheels or plastics.", "Trail", "Manual", "Read the number after KLX. That number is the class.", "No KLX-only part is in the catalog yet."),
    "kawasaki-versys": bike("Kawasaki Versys is a touring-adventure family. Versys 650 and Versys 1000 are the usual split.", "Adventure touring", "Manual", "650 or 1000. The X-300, where sold, is a third bike.", "No Versys-only part is in the catalog yet."),
    "re-himalayan": bike("The Royal Enfield Himalayan is an adventure bike. The first generation is the 411. The later Himalayan is the 450.", "Adventure", "Manual", "411 or 450. They do not share the engine or the wheels.", "No Himalayan-only part is in the catalog yet."),
    "re-scram": bike("The Royal Enfield Scram is the scrambler built from the Himalayan 411 platform.", "Scrambler", "Manual", "411 class. It is not the Himalayan 450.", "No Scram-only part is in the catalog yet."),
    "bmw-gs": bike("BMW GS is the adventure range: G 310 GS, F 750 GS, F 850 GS, and the large R GS.", "Adventure", "Manual", "Read the full GS name. A 310 and an R 1300 GS do not share a single part.", "No GS-only part is in the catalog yet."),
    "triumph-tiger": bike("Triumph Tiger is an adventure family. Tiger Sport 660, Tiger 900, and Tiger 1200 are separate models.", "Adventure", "Manual", "The number in the name is the class. Match that number.", "No Tiger-only part is in the catalog yet."),
    "husqvarna": bike("Husqvarna road bikes here include Svartpilen, Vitpilen, and Norden. Dirt models are a different catalog.", "Naked, scrambler, or adventure", "Manual", "Read the model. A Svartpilen 401 and a Norden 901 are not the same fitment.", "No Husqvarna-only part is in the catalog yet."),

    "re-classic": bike("The Royal Enfield Classic is the retro single most riders mean in the 350 class.", "Classic", "Manual", "350 on the current Classic. Older 500 Classics are a different engine.", "No Classic-only part is in the catalog yet."),
    "re-meteor": bike("The Royal Enfield Meteor is a cruiser-styled 350 on the same generation as the current Classic.", "Cruiser", "Manual", "350 class. It does not share every part with a Classic or a Hunter.", "No Meteor-only part is in the catalog yet."),
    "re-hunter": bike("The Royal Enfield Hunter 350 is the lighter roadster in the 350 family.", "Roadster", "Manual", "350 class. Metro and Rebel trims still share the Hunter chassis, but read the trim if you are buying body parts.", "No Hunter-only part is in the catalog yet."),
    "honda-rebel": bike("The Honda Rebel is a cruiser. Rebel 500 and Rebel 1100 are both sold under that name.", "Cruiser", "Manual", "500 or 1100. The number is on the side cover.", "No Rebel-only part is in the catalog yet."),
    "honda-shadow": bike("The Honda Shadow is an older cruiser line, with several displacements over the years.", "Cruiser", "Manual", "Read the engine size on the papers. Shadow 400 and larger Shadows do not share parts.", "No Shadow-only part is in the catalog yet."),
    "kawasaki-vulcan": bike("Kawasaki Vulcan is a cruiser family. The Vulcan S is the 650 most riders mean, and other Vulcans are larger.", "Cruiser", "Manual", "650 on the Vulcan S. Read the model if the tank badge only says Vulcan.", "No Vulcan-only part is in the catalog yet."),
    "kawasaki-eliminator": bike("The Kawasaki Eliminator is a light cruiser. The current bike riders mean is the Eliminator in the 450 to 500 class.", "Cruiser", "Manual", "Read the exact year. The modern Eliminator replaced a much older model of the same name.", "No Eliminator-only part is in the catalog yet."),
    "harley-davidson": bike("Harley-Davidson is a brand, not one motorcycle. Sportster, Softail, and Touring bikes do not share fitment.", "Cruiser", "Manual", "Read the model name. A Sportster 883 and a Road Glide are different motorcycles.", "No Harley-only part is in the catalog yet."),
    "triumph-classic": bike("Triumph Modern Classics covers Bonneville, Street Twin, Speed Twin, Scrambler, and Thruxton.", "Classic", "Manual", "900 and 1200 classes are both in this family. Read the full model.", "No Triumph-classic part is in the catalog yet."),

    "honda-middleweight": bike("Honda middleweight on this page means the 500 class and the bikes just above it, such as CB500 and CBR500, not a Gold Wing and not a Wave.", "Middleweight", "Manual", "Start from the model code. 500, 650, and 750 Hondas do not share chains, tires, or fairings.", "No single middleweight part is in the catalog yet."),
    "yamaha-middleweight": bike("Yamaha middleweight here means the 500 to 900 class, such as MT-07 and R7, not an NMAX and not an R1.", "Middleweight", "Manual", "Read the model. An MT-07 and a Tracer 9 are different fitments.", "No single middleweight part is in the catalog yet."),
    "suzuki-middleweight": bike("Suzuki middleweight here means bikes such as the GSX-8S and the SV650, not a Smash and not a Hayabusa.", "Middleweight", "Manual", "Read the model code before you order a chain, a tire, or an exhaust.", "No single middleweight part is in the catalog yet."),
    "kawasaki-middleweight": bike("Kawasaki middleweight here means the 400 to 650 class, such as Ninja 400, Z650, and Versys 650.", "Middleweight", "Manual", "The number after Ninja, Z, or Versys is the class. Use that number.", "No single middleweight part is in the catalog yet."),
    "bmw": bike("BMW on this page is the brand, separate from the GS button. G, F, and R road bikes each have their own parts.", "Big bike", "Manual", "Read the full model, such as G 310 R or S 1000 R. The roundel is not a size.", "No BMW-only part is in the catalog yet."),
    "ducati": bike("Ducati covers Scrambler, Monster, Panigale, Multistrada, and Diavel. None of those share a parts list.", "Big bike", "Manual", "Read the model and the year. A Scrambler 800 and a Panigale V4 are different motorcycles.", "No Ducati-only part is in the catalog yet."),
    "aprilia": bike("Aprilia here covers RS and Tuono sport bikes and the scooters that wear the same brand. They are not one fitment.", "Sport or scooter", "Manual on the sport bikes, CVT on the scooters", "Read the model. An RS 457 and an SR scooter do not share parts.", "No Aprilia-only part is in the catalog yet."),
    "triumph": bike("Triumph on this button is the wider brand, beyond the Tiger and the Modern Classics buttons.", "Big bike", "Manual", "Read the model name. Street Triple, Speed Triple, and Rocket 3 are different bikes.", "Use the Tiger or Modern Classics button when that is the bike you ride. This button is the rest of the range.")
  };
})();
